### ISSUE TITLE
[Enhancement] Provider Package for Seren

### ISSUE THREAD

**Issue by Goldenfreddy0703** [Daniel-Griffiths/9anime-scraper#111]
Hi i am so so sorry for bothering you and this is not an issue but an enhancement for Real Debrid users and Seren users. There is an application called kodi and there is this addon called Seren inwhich users can watch Movies and TV Shows if they are Real Debrid users and what Seren is using is Provider Packages. Is there a possible chance or a possibility to turn your 9anime scrapper into a provider package for Seren so that people can watch 9anime on kodi with the 9anime stream links? I love what you have created and this could be a big use for the Seren people for kodi which will provide the best anime if this could happen. If you could turn your 9anime scaper to a provider package, that would be the best.

**Comment by Daniel-Griffiths** [comment]
Hi @Goldenfreddy0703  thanks for you comment.

Seren is not something I am familiar with and adding support for it is beyond the scope of this package. However, I am happy for anyone to use this lib to make an addon if they so choose.

**Comment by Goldenfreddy0703** [comment]
Hey thank you so much for responding and i believe in the future that someone could possibly make an addon with this lib someday, This is a great scrapper and i support you for this. Thank you very much.
